server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSl=false
    username: root
    password: a1990520
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001
    prefer-ip-address: true
    #发送心跳
#    lease-renewal-interval-in-seconds:
#    #时间间隔
#    lease-expiration-duration-in-seconds:


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.czz.springcloud.entities







